<?php
/**
 * @author    Marcin Frymark
 * @email     contact@alekseon.com
 * @company   Alekseon
 * @website   www.alekseon.com
 */
?>
<div class="box-left">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('alekseon_mailTransport')->__('Mail Information') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><label><?php echo Mage::helper('alekseon_mailTransport')->__('Subject') ?></label></td>
                    <td class="value"><strong><?php echo $this->escapeHtml($this->getSubject()) ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('alekseon_mailTransport')->__('Sent At') ?></label></td>
                    <td class="value"><strong><?php echo $this->getSentAt() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('alekseon_mailTransport')->__('Sent From') ?></label></td>
                    <td class="value"><strong><?php echo $this->getSentFrom() ?></strong></td>
                </tr>
                <?php if ($this->getController()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('alekseon_mailTransport')->__('Controller') ?></label></td>
                        <td class="value"><strong><?php echo $this->getController() ?></strong></td>
                    </tr>
                <?php endif ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('alekseon_mailTransport')->__('Status') ?></label></td>
                    <?php if ($this->getStatus()): ?>
                        <td class="value"><span class="grid-severity-notice" style="width:150px"><span><?php echo Mage::helper('alekseon_mailTransport')->__('Success') ?></span></span></td>
                    <?php else: ?>
                        <td class="value"><span class="grid-severity-critical" style="width:150px"><span><?php echo Mage::helper('alekseon_mailTransport')->__('Failed') ?></span></span></td>
                    <?php endif ?>
                </tr>
                <?php if ($this->getComment()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('alekseon_mailTransport')->__('Comment') ?></label></td>
                        <td class="value"><strong><?php echo $this->getComment() ?></strong></td>
                    </tr>
                <?php endif ?>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('alekseon_mailTransport')->__('Transport Type') ?></label></td>
                    <td class="value"><strong><?php echo $this->getTransportType() ?></strong></td>
                </tr>
                <tr>
                    <td class="label"><label><?php echo Mage::helper('alekseon_mailTransport')->__('Used Template') ?></label></td>
                    <td class="value"><strong><?php echo $this->getUsedTemplate() ?></strong></td>
                </tr>
                <?php if ($this->getTemplateType()): ?>
                    <tr>
                        <td class="label"><label><?php echo Mage::helper('alekseon_mailTransport')->__('Template Type') ?></label></td>
                        <td class="value"><strong><?php echo $this->getTemplateType() ?></strong></td>
                    </tr>
                <?php endif ?>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('alekseon_mailTransport')->__('Sender') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <?php foreach($this->getSender() as $sender): ?>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($sender->getName()) ?></label></td>
                        <td class="value"><a href="mailto:<?php echo $this->escapeHtml($sender->getEmail()) ?>"><strong><?php echo $this->escapeHtml($sender->getEmail()) ?></strong></a></td>
                    </tr>
                <?php endforeach ?>
            </table>
        </div>
    </div>
</div>
<div class="box-right">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-account"><?php echo Mage::helper('alekseon_mailTransport')->__('Receipients') ?></h4>
        </div>
        <div class="fieldset">
            <table cellspacing="0" class="form-list">
                <?php foreach($this->getReceipients() as $receipient): ?>
                    <tr>
                        <td class="label"><label><?php echo $this->escapeHtml($receipient->getName()) ?></label></td>
                        <td class="value"><a href="mailto:<?php echo $this->escapeHtml($receipient->getEmail()) ?>"><strong><?php echo $this->escapeHtml($receipient->getEmail()) ?></strong></a></td>
                    </tr>
                <?php endforeach ?>
                <?php foreach($this->getBccReceipients() as $receipients): ?>
                    <tr>
                        <td class="label"><label>[Bcc] <?php echo $this->escapeHtml($receipients->getName()) ?></label></td>
                        <td class="value"><a href="mailto:<?php echo $this->escapeHtml($receipients->getEmail()) ?>"><strong><?php echo $this->escapeHtml($receipients->getEmail()) ?></strong></a></td>
                    </tr>
                <?php endforeach ?>
            </table>
        </div>
    </div>
</div>
<div class="clear"></div>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-account"><?php echo Mage::helper('alekseon_mailTransport')->__('Mail Body') ?></h4>
    </div>
    <div class="fieldset">
        <?php if ($this->isContentConfidential()): ?>
            <?php echo Mage::helper('alekseon_mailTransport')->__('Content of this email is confidential.') ?>
        <?php else: ?>
            <iframe src="<?php echo $this->getMailBodyIframeUrl() ?>" frameborder="1" style="width:100%; height:600px;">
                <p><?php echo $this->__('Your browser does not support iframes.') ?></p>
            </iframe>
        <?php endif ?>
    </div>
</div>